// carousel
export const FETCH_TOP_PRODUCTS_LIST_REQUEST = 'FETCH_TOP_PRODUCTS_LIST_REQUEST'
export const FETCH_TOP_PRODUCTS_LIST_SUCCESS = 'FETCH_TOP_PRODUCTS_LIST_SUCCESS'
export const FETCH_TOP_PRODUCTS_LIST_FAILURE = 'FETCH_TOP_PRODUCTS_LIST_FAILURE'
export const FETCH_TOP_PRODUCTS_REQUEST = 'FETCH_TOP_PRODUCTS_REQUEST'
export const FETCH_TOP_PRODUCTS_SUCCESS = 'FETCH_TOP_PRODUCTS_SUCCESS'
export const FETCH_TOP_PRODUCTS_FAILURE = 'FETCH_TOP_PRODUCTS_FAILURE'

// cart

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const CLEAR_CART = 'CLEAR_CART'

// categories

export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST'
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS'
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE'
export const CATALOG_LOCATION = 'CATALOG_LOCATION'

// products

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const SORTING_PRODUCTS = 'SORTING_PRODUCTS'
export const RESET_SORTING = 'RESET_SORTING'