// carousel
export const FETCH_TOP_PRODUCTS_LIST_REQUEST = 'FETCH_TOP_PRODUCTS_LIST_REQUEST'
export const FETCH_TOP_PRODUCTS_LIST_SUCCESS = 'FETCH_TOP_PRODUCTS_LIST_SUCCESS'
export const FETCH_TOP_PRODUCTS_LIST_FAILURE = 'FETCH_TOP_PRODUCTS_LIST_FAILURE'
export const FETCH_TOP_PRODUCTS_REQUEST = 'FETCH_TOP_PRODUCTS_REQUEST'
export const FETCH_TOP_PRODUCTS_SUCCESS = 'FETCH_TOP_PRODUCTS_SUCCESS'
export const FETCH_TOP_PRODUCTS_FAILURE = 'FETCH_TOP_PRODUCTS_FAILURE'

// products

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const SORTING_PRODUCTS = 'SORTING_PRODUCTS'
export const RESET_SORTING = 'RESET_SORTING'